platform :ios, '17.0'


target 'Vault' do
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleSignIn'

  target 'VaultTests' do
    inherit! :search_paths
  end

  target 'VaultUITests' do
    inherit! :search_paths
  end
end

target 'ShareExtension' do
  use_frameworks!
  pod 'Firebase/Core'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
